"""
Task Executor - Executes agent-generated tasks
"""
import logging
import time
from datetime import datetime
from typing import Dict, Any, Optional
from pathlib import Path

from config import LOG_DIR, MEMORY_DIR
from tasks.tools import FileOperationTool, DataAnalysisTool, SuggestionTool, LoggingTool

logger = logging.getLogger(__name__)


class TaskExecutor:
    """Executes tasks generated by the ReAct agent"""
    
    def __init__(self):
        self.output_dir = Path(MEMORY_DIR) / "task_outputs"
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def execute(self, task: Dict[str, Any], memory_stats: Dict[str, Any] = None, 
                history: list = None) -> Dict[str, Any]:
        """
        Execute a task and return result
        
        Args:
            task: Task specification from agent
            memory_stats: Current memory statistics
            history: Execution history for analysis
        
        Returns:
            Dict with execution result
        """
        start_time = time.time()
        logger.info(f"Starting task execution: {task.get('title', 'Unknown')}")
        
        try:
            task_type = task.get("type", "analysis")
            
            if task_type == "file_operation":
                result = self._execute_file_operation(task)
            elif task_type == "data_analysis":
                result = self._execute_data_analysis(task, memory_stats, history)
            elif task_type == "suggestion":
                result = self._execute_suggestion_generation(task, memory_stats)
            elif task_type == "research":
                result = self._execute_research(task)
            else:
                result = self._execute_generic_task(task)
            
            # Add execution metadata
            duration_ms = int((time.time() - start_time) * 1000)
            result["duration_ms"] = duration_ms
            result["executed_at"] = datetime.utcnow().isoformat() + "Z"
            
            logger.info(f"Task completed: {task.get('title')} ({duration_ms}ms)")
            return result
            
        except Exception as e:
            logger.error(f"Task execution failed: {e}", exc_info=True)
            return {
                "status": "failed",
                "error": str(e),
                "task_id": task.get("task_id"),
                "duration_ms": int((time.time() - start_time) * 1000),
                "executed_at": datetime.utcnow().isoformat() + "Z"
            }
    
    def _execute_file_operation(self, task: Dict[str, Any]) -> Dict[str, Any]:
        """Execute file-related tasks"""
        operation = task.get("operation", "create")
        filename = task.get("filename", f"output_{datetime.utcnow().timestamp()}.txt")
        content = task.get("content", task.get("description", "Generated by Ellie"))
        
        if operation == "create":
            result = FileOperationTool.create_file(filename, content, str(self.output_dir))
        elif operation == "append":
            result = FileOperationTool.append_to_file(filename, content, str(self.output_dir))
        elif operation == "read":
            result = FileOperationTool.read_file(filename, str(self.output_dir))
        else:
            result = {"success": False, "error": f"Unknown operation: {operation}"}
        
        return {
            "status": "completed" if result.get("success") else "failed",
            "task_id": task.get("task_id"),
            "operation": operation,
            "result": result,
            "output_file": result.get("filepath")
        }
    
    def _execute_data_analysis(self, task: Dict[str, Any], 
                               memory_stats: Dict[str, Any], 
                               history: list) -> Dict[str, Any]:
        """Execute data analysis tasks"""
        analysis_type = task.get("analysis_type", "summary")
        
        results = {}
        
        if analysis_type == "execution_summary" and history:
            results["execution_analysis"] = DataAnalysisTool.analyze_execution_history(history)
        
        if memory_stats:
            results["statistics"] = memory_stats
        
        # Generate daily report
        if history and memory_stats:
            report_content = DataAnalysisTool.generate_daily_report(memory_stats, history)
            report_file = f"daily_report_{datetime.utcnow().strftime('%Y%m%d')}.md"
            file_result = FileOperationTool.create_file(report_file, report_content, str(self.output_dir))
            
            if file_result.get("success"):
                results["report_file"] = file_result.get("filepath")
        
        return {
            "status": "completed",
            "task_id": task.get("task_id"),
            "analysis_type": analysis_type,
            "result": results
        }
    
    def _execute_suggestion_generation(self, task: Dict[str, Any], 
                                      memory_stats: Dict[str, Any]) -> Dict[str, Any]:
        """Generate suggestions for improvement"""
        suggestions = []
        
        # Generate internal improvement suggestions
        if memory_stats:
            suggestions.extend(SuggestionTool.generate_improvement_suggestions(memory_stats))
        
        # Generate user-facing suggestions
        suggestions.extend(SuggestionTool.generate_user_suggestions(""))
        
        # Save suggestions to file
        suggestion_content = "# Daily Suggestions\n\n"
        for i, suggestion in enumerate(suggestions, 1):
            suggestion_content += f"{i}. {suggestion}\n"
        
        suggestion_file = f"suggestions_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.md"
        file_result = FileOperationTool.create_file(suggestion_file, suggestion_content, str(self.output_dir))
        
        return {
            "status": "completed",
            "task_id": task.get("task_id"),
            "suggestion_count": len(suggestions),
            "suggestions": suggestions,
            "output_file": file_result.get("filepath") if file_result.get("success") else None
        }
    
    def _execute_research(self, task: Dict[str, Any]) -> Dict[str, Any]:
        """Execute research/information gathering tasks"""
        research_topic = task.get("research_topic", task.get("description", "General research"))
        
        # Create research log
        research_log = f"""# Research: {research_topic}
Generated: {datetime.utcnow().isoformat()}Z

## Findings
This is a placeholder for research findings.
In a full implementation, this would perform web searches and summarization.

## Key Points
- Research topic: {research_topic}
- Status: Documented in memory
- Recommendations: Available in agent memory

## Next Steps
Monitor agent outputs in the daily reports for research-based insights.
"""
        
        research_file = f"research_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.md"
        file_result = FileOperationTool.create_file(research_file, research_log, str(self.output_dir))
        
        return {
            "status": "completed",
            "task_id": task.get("task_id"),
            "research_topic": research_topic,
            "output_file": file_result.get("filepath") if file_result.get("success") else None
        }
    
    def _execute_generic_task(self, task: Dict[str, Any]) -> Dict[str, Any]:
        """Execute generic/analysis tasks"""
        # Create task completion log
        task_log = f"""# Task Execution Log
Task: {task.get('title', 'Unknown')}
ID: {task.get('task_id', 'unknown')}
Type: {task.get('type', 'generic')}
Time: {datetime.utcnow().isoformat()}Z

## Description
{task.get('description', 'No description')}

## Expected Impact
{task.get('expected_impact', 'Task completed and logged')}

## Status
✓ Task executed and recorded in agent memory
"""
        
        task_file = f"task_{task.get('task_id', 'generic')}_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.md"
        file_result = FileOperationTool.create_file(task_file, task_log, str(self.output_dir))
        
        return {
            "status": "completed",
            "task_id": task.get("task_id"),
            "result": "Task analyzed and logged",
            "output_file": file_result.get("filepath") if file_result.get("success") else None
        }
